### ISSUE TITLE
PE concept set

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#11]
- [ ] Consider including 4236271 Recurrent pulmonary embolism
- [ ] Consider including 435026, Obstetric pulmonary embolism
- [ ] Consider including 43530934 Induced termination of pregnancy complicated by pulmonary embolism
- [ ] Consider including 433832 Obstetric blood-clot pulmonary embolism

**Comment by edward-burn** [comment]
@daniprietoalhambra for 4236271 Recurrent pulmonary embolism, this I suppose is similar to 46271900 Recurrent deep vein thrombosis in #9 and #10?

**Comment by daniprietoalhambra** [comment]
Yes indeed. All to be included

Dani

Dani Prieto-Alhambra
Professor of Pharmaco- and Device Epidemiology
NIHR Senior Research Fellow
CSM-NDORMS, University of Oxford

On 14 Apr 2021, at 17:03, edward-burn ***@***.***> wrote:

﻿

@daniprietoalhambra<https://github.com/daniprietoalhambra> for 4236271 Recurrent pulmonary embolism, this I suppose is similar to 46271900 Recurrent deep vein thrombosis in #9<https://github.com/oxford-pharmacoepi/CovCoagOutcomeDiagnostics/issues/9> and #10<https://github.com/oxford-pharmacoepi/CovCoagOutcomeDiagnostics/issues/10>?

**Comment by edward-burn** [comment]
- [x] Include 4236271 Recurrent pulmonary embolism
- [ ] Consider including 435026, Obstetric pulmonary embolism
- [ ] Consider including 43530934 Induced termination of pregnancy complicated by pulmonary embolism
- [ ] Consider including 433832 Obstetric blood-clot pulmonary embolism

**Comment by edward-burn** [comment]
- [x] Include 4236271 Recurrent pulmonary embolism
