### ISSUE TITLE
Ischemic stroke concept set

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#12]
- [ ] Consider including source code 45420378
- [ ] Remove 372435 Periventricular leukomalacia
- [ ] Remove 4129534 Pituitary apoplexy
- [ ] Remove 4046089 Vascular dementia of acute onset

**Comment by edward-burn** [comment]
- [ ] Consider including source code 45420378
- [x] Remove 372435 Periventricular leukomalacia
- [x] Remove 4129534 Pituitary apoplexy
- [x] Remove 4046089 Vascular dementia of acute onset

**Comment by edward-burn** [comment]
@daniprietoalhambra source code 45420378 maps to 372924 "Cerebral artery occlusion", what do you think?

**Comment by daniprietoalhambra** [comment]
Include it please

**Comment by edward-burn** [comment]
- [x] Add 372924 Cerebral artery occlusion
- [x] Remove 372435 Periventricular leukomalacia
- [x] Remove 4129534 Pituitary apoplexy
- [x] Remove 4046089 Vascular dementia of acute onset
