### ISSUE TITLE
Units for platelet count in IPCI

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#32]
For IPCI we are identifying platelet measurements but they are not contributing to the index event breakdown. @PRijnbeek can you please check the unit concept being used for platelet measurements (3024929 "Platelets [#/volume] in Blood by Automated count" in IPCI?

**Comment by PRijnbeek** [comment]
We do not have a unit concept since the source did not have it, but it looks like 10^9/L values are 1%=100, 50%=261, 99%=536, seems as expected from normal limits

**Comment by PRijnbeek** [comment]
<img width="799" alt="image" src="https://user-images.githubusercontent.com/7252105/115709187-3160ee00-a371-11eb-86c1-a4a4701ae57d.png">

**Comment by edward-burn** [comment]
Thanks @PRijnbeek, as none of the other databases in the study uses the same concept id for this measurement, I will not require a unit concept for it and will specify the values based on the above
