### ISSUE TITLE
Heparin codes to add

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#35]
Further Heparin codes to add:
- [x] DAGermany- Add to HEPARIN: 41405875, 41404759 , 41405544, 41405132 (all RxNormExtension)       
- [ ] LPDItaly- Add to HEPARIN: 2040308827 (source)
- [ ] IPCI - Add to HEPARIN: 2061027375, 2061032166, 2061029793, 2061053848, 2061049255, 2061029785, 2061038423, 2013639099 (all source ZIndex codes)

**Comment by edward-burn** [comment]
@PRijnbeek can you please check what the above source codes in IPCI map to?

**Comment by edward-burn** [comment]
@kmkostka @hms1 can you please check what the above source code in LPDItaly maps to?

**Comment by hms1** [comment]
> @kmkostka @hms1 can you please check what the above source code in LPDItaly maps to?

It looks like there is a mapping error.

```{sql}
SELECT concept_id_1, c1.concept_name, relationship_id, concept_id_2, c2.concept_name
FROM prod_itlpd.full_202007_omop_v5.concept_relationship cr
LEFT JOIN full_202007_omop_v5.concept c1 on c1.concept_id = cr.concept_id_1
LEFT JOIN full_202007_omop_v5.concept c2 on c2.concept_id = cr.concept_id_2
WHERE concept_id_1 = 2040308827
AND relationship_id = 'Maps to';
```

concept_id_1 | concept_name | relationship_id | concept_id_2 | concept_name
-- | -- | -- | -- | --
2040308827 | CLEXANE*6SIR 4000UI   0,4ML\|SOLUZIONE INIETTABILE | Maps to | 19082346 | entacapone 200 MG Oral Tablet

**Comment by edward-burn** [comment]
> 
> 
> > @kmkostka @hms1 can you please check what the above source code in LPDItaly maps to?
> 
> It looks like there is a mapping error.
> 
> ```
> SELECT concept_id_1, c1.concept_name, relationship_id, concept_id_2, c2.concept_name
> FROM prod_itlpd.full_202007_omop_v5.concept_relationship cr
> LEFT JOIN full_202007_omop_v5.concept c1 on c1.concept_id = cr.concept_id_1
> LEFT JOIN full_202007_omop_v5.concept c2 on c2.concept_id = cr.concept_id_2
> WHERE concept_id_1 = 2040308827
> AND relationship_id = 'Maps to';
> ```
> 
> concept_id_1 	concept_name 	relationship_id 	concept_id_2 	concept_name
> 2040308827 	CLEXANE*6SIR 4000UI 0,4ML|SOLUZIONE INIETTABILE 	Maps to 	19082346 	entacapone 200 MG Oral Tablet

Thanks @hms1, as this code is used for such a small number of records we will omit it

**Comment by edward-burn** [comment]
Add the following codes for IPCI:
- [x] 19001016
- [x] 19001016
- [x] 40176348
- [x] 19001019
- [x] 40180717
- [x] 43623979
- [x] 19001016
- [x] 40160948
