### ISSUE TITLE
Long filenames issue?

### ISSUE THREAD

**Issue by PRijnbeek** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#4]
Error: Cannot find '[EB] CovCoag Disseminated intravascular coagulation- during hospitalisation.sql' in the 'sql/sql_server' folder of the 'diagCovCoagOutcomes' package.

**Comment by edward-burn** [comment]
I have shortened all the names for the cohorts, so hopefully this shouldn´t be a problem any more. As I´m not sure what the maximum limit is, I will leave this issue open until you have had a successful run of the package

**Comment by edward-burn** [comment]
The package has now been run successfully
