### ISSUE TITLE
Warning for SQL to check

### ISSUE THREAD

**Issue by PRijnbeek** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#5]
Creating cohort: [EB] CovCoag Cerebral venous sinus thrombosis
Warning: warning: Parameter 'results_database_schema.cohort_inclusion' not found in SQL

Warning: warning: Parameter 'results_database_schema.cohort_inclusion_result' not found in SQL

Warning: warning: Parameter 'results_database_schema.cohort_inclusion_stats' not found in SQL

Warning: warning: Parameter 'results_database_schema.cohort_summary_stats' not found in SQL

**Comment by edward-burn** [comment]
This should now be fixed in the latest version
