### ISSUE TITLE
Check JSON and SQL are alligned

### ISSUE THREAD

**Issue by PRijnbeek** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#6]
[errorReportR.txt](https://github.com/oxford-pharmacoepi/CovCoagOutcomeDiagnostics/files/6280416/errorReportR.txt)

Fetching inclusion statistics took 4.86 secs
Starting concept set diagnostics
Cohort Definition expression does not have a concept set expression. Skipping Cohort: [EB] CovCoag Death
Warning: warning: Unknown or uninitialised column: `cohortFullName`.

Error in combineConceptSetsFromCohorts(subset) : 
  Mismatch in concept set IDs between SQL and JSON for cohort

**Comment by kmkostka** [comment]
I got the same error in all 3 of my runs from this version of the package (LPD France, LPD Belgium, DA Germany).

````
Warning: warning: Unknown or uninitialised column: `cohortFullName`.
Error in combineConceptSetsFromCohorts(subset) : 
  Mismatch in concept set IDs between SQL and JSON for cohort 
  ````

**Comment by edward-burn** [comment]
Apologies, this should now be fixed in the latest version
