### ISSUE TITLE
DVT narrow concept set

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CovCoagOutcomeDiagnostics#9]

**Comment by edward-burn** [comment]
- [ ] Remove 4149782 Thrombosis of vein of lower limb
- [ ] Consider including 435887 Antepartum deep vein thrombosis
- [ ] Consider including 46271900 Recurrent deep vein thrombosis
- [ ] Consider including 4189004 Deep vein thrombosis of leg related to intravenous drug use
- [ ] Consider including source code 45453350 (READ) Thrombophlebitis of deep veins of lower extremity

**Comment by edward-burn** [comment]
@daniprietoalhambra the source Read code 45453350 maps to the standard 4221821 "Thrombophlebitis of deep veins of lower extremity". This is not currently in either our narrow or broad DVT concept set. Are you happy for me to add it to both?

**Comment by edward-burn** [comment]
- [x] Remove 4149782 Thrombosis of vein of lower limb
- [ ] Consider including 435887 Antepartum deep vein thrombosis
- [ ] Consider including 46271900 Recurrent deep vein thrombosis
- [ ] Consider including 4189004 Deep vein thrombosis of leg related to intravenous drug use
- [ ] Consider including source code 45453350 (READ) Thrombophlebitis of deep veins of lower extremity

**Comment by daniprietoalhambra** [comment]
Yes please let us add this
Bw

Dani Prieto-Alhambra
Professor of Pharmaco- and Device Epidemiology
NIHR Senior Research Fellow
CSM-NDORMS, University of Oxford

On 14 Apr 2021, at 16:54, edward-burn ***@***.***> wrote:

﻿

@daniprietoalhambra<https://github.com/daniprietoalhambra> the source Read code 45453350 maps to the standard 40198004 "Thrombophlebitis of deep veins of lower extremity". This is not currently in either our narrow or broad DVT concept set. Are you happy for me to add it to both?

**Comment by edward-burn** [comment]
- [x] Remove 4149782 Thrombosis of vein of lower limb
- [ ] Consider including 435887 Antepartum deep vein thrombosis
- [ ] Consider including 46271900 Recurrent deep vein thrombosis
- [ ] Consider including 4189004 Deep vein thrombosis of leg related to intravenous drug use
- [x] Include source code 45453350 (READ) Thrombophlebitis of deep veins of lower extremity

**Comment by edward-burn** [comment]
- [x] Remove 4149782 Thrombosis of vein of lower limb
- [ ] Consider including 435887 Antepartum deep vein thrombosis
- [x] Include 46271900 Recurrent deep vein thrombosis
- [ ] Consider including 4189004 Deep vein thrombosis of leg related to intravenous drug use
- [x] Include source code 45453350 (READ) Thrombophlebitis of deep veins of lower extremity

**Comment by edward-burn** [comment]
- [x] Remove 4149782 Thrombosis of vein of lower limb
- [x] Include 46271900 Recurrent deep vein thrombosis
- [x] Include 4189004 Deep vein thrombosis of leg related to intravenous drug use
- [x] Include source code 45453350 (READ) Thrombophlebitis of deep veins of lower extremity
